name = "hunterguide-astro"
compatibility_date = "2026-05-12"
workers_dev = true

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "090124c88aa44179a171bb547aea0286"
preview_id = "090124c88aa44179a171bb547aea0286"
